<?php

namespace App\Http\Resources;

use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;

class InvoiceResource extends JsonResource
{
    /**
     * Transform the resource into an array.
     *
     * @param  Request  $request
     */
    public function toArray($request): array
    {
        return [
            'id' => $this->id,
            'invoice_date' => $this->invoice_date,
            'formatted_invoice_date' => $this->formatted_invoice_date,
            'due_date' => $this->due_date,
            'formatted_due_date' => $this->formatted_due_date,
            'invoice_number' => $this->invoice_number,
            'reference_number' => $this->reference_number,
            'status' => $this->status,
            'paid_status' => $this->paid_status,
            'tax_per_item' => $this->tax_per_item,
            'tax_included' => $this->tax_included,
            'discount_per_item' => $this->discount_per_item,
            'notes' => $this->notes,
            'discount_type' => $this->discount_type,
            'discount' => $this->discount,
            'discount_val' => $this->discount_val,
            'sub_total' => $this->sub_total,
            'total' => $this->total,
            'tax' => $this->tax,
            'due_amount' => $this->due_amount,
            'sent' => $this->sent,
            'viewed' => $this->viewed,
            'unique_hash' => $this->unique_hash,
            'template_name' => $this->template_name,
            'customer_id' => $this->customer_id,
            'consignee_customer_id' => $this->consignee_customer_id,
            'recurring_invoice_id' => $this->recurring_invoice_id,
            'sequence_number' => $this->sequence_number,
            'exchange_rate' => $this->exchange_rate,
            'base_discount_val' => $this->base_discount_val,
            'base_sub_total' => $this->base_sub_total,
            'base_total' => $this->base_total,
            'creator_id' => $this->creator_id,
            'base_tax' => $this->base_tax,
            'base_due_amount' => $this->base_due_amount,
            'currency_id' => $this->currency_id,
            'invoice_pdf_url' => $this->invoicePdfUrl,
            'sales_tax_type' => $this->sales_tax_type,
            'sales_tax_address_type' => $this->sales_tax_address_type,
            'overdue' => $this->overdue,

            // Transport fields (native columns â€” used by lr_receipt, lorry_receipt templates)
            'from_code' => $this->from_code,
            'from_name' => $this->from_name,
            'to_code' => $this->to_code,
            'to_name' => $this->to_name,
            'truck_no' => $this->truck_no,
            'mode_of_payment' => $this->mode_of_payment,
            'gst_tax_payable_by' => $this->gst_tax_payable_by,
            'description_of_goods' => $this->description_of_goods,
            'hsn_code' => $this->hsn_code,
            'eway_bill_no' => $this->eway_bill_no,
            'actual_weight' => $this->actual_weight,
            'charged_weight' => $this->charged_weight,
            'no_of_articles' => $this->no_of_articles,
            'packing' => $this->packing,
            'basic_freight' => $this->basic_freight,
            'hamali' => $this->hamali,
            'fov' => $this->fov,
            'local_collection' => $this->local_collection,
            'door_delivery' => $this->door_delivery,
            'docket_charge' => $this->docket_charge,
            'other_charge' => $this->other_charge,
            'net_amount' => $this->net_amount,
            'no_of_pages' => $this->no_of_pages,
            'no_of_packages' => $this->no_of_packages,
            'distance_kms' => $this->distance_kms,
            'rate' => $this->rate,
            'regd_at' => $this->regd_at,
            'body_type' => $this->body_type,
            'make' => $this->make,
            'vehicle_model' => $this->vehicle_model,
            'colour' => $this->colour,
            'chasis_no' => $this->chasis_no,
            'engine_no' => $this->engine_no,
            'fitness_validity' => $this->fitness_validity,
            'road_permit_no' => $this->road_permit_no,
            'permit_date' => $this->permit_date,
            'permit_valid_in' => $this->permit_valid_in,
            'permit_status_upto' => $this->permit_status_upto,
            'insured_with' => $this->insured_with,
            'insurance_division_no' => $this->insurance_division_no,
            'insurance_certificate_no' => $this->insurance_certificate_no,
            'insurance_valid_upto' => $this->insurance_valid_upto,
            'owner_code' => $this->owner_code,
            'owner_name' => $this->owner_name,
            'owner_address' => $this->owner_address,
            'owner_phone' => $this->owner_phone,
            'owner_bank_account_no' => $this->owner_bank_account_no,
            'owner_pan_no' => $this->owner_pan_no,
            'financer_name' => $this->financer_name,
            'financer_address' => $this->financer_address,
            'driver_name' => $this->driver_name,
            'driver_address' => $this->driver_address,
            'driver_place' => $this->driver_place,
            'driver_licence_no' => $this->driver_licence_no,
            'driver_licence_date' => $this->driver_licence_date,
            'driver_licence_issued_by' => $this->driver_licence_issued_by,
            'driver_rto_address' => $this->driver_rto_address,
            'driver_valid_up_to' => $this->driver_valid_up_to,
            'driver_bank_account_no' => $this->driver_bank_account_no,
            'broker_name' => $this->broker_name,
            'broker_address' => $this->broker_address,
            'broker_pan_no' => $this->broker_pan_no,
            'broker_phone_no' => $this->broker_phone_no,
            'broker_bank_account_no' => $this->broker_bank_account_no,
            'advice_no' => $this->advice_no,
            'advice_date' => $this->advice_date,
            'destination_broker_name' => $this->destination_broker_name,
            'destination_broker_address' => $this->destination_broker_address,
            'paid_to' => $this->paid_to,
            'lorry_hire_amount' => $this->lorry_hire_amount,
            'other_charges_amount' => $this->other_charges_amount,
            'gross_hire_rupees' => $this->gross_hire_rupees,
            'gross_hire_amount' => $this->gross_hire_amount,
            'advance_cash_cheque_no' => $this->advance_cash_cheque_no,
            'advance_on' => $this->advance_on,
            'advance_bank' => $this->advance_bank,
            'advance_amount' => $this->advance_amount,
            'balance_payable_at' => $this->balance_payable_at,
            'balance_payable_code' => $this->balance_payable_code,
            'balance_rupees' => $this->balance_rupees,
            'balance_amount' => $this->balance_amount,
            'balance_rupees_only' => $this->balance_rupees_only,
            'hire_passed_by' => $this->hire_passed_by,
            'hire_certified_by' => $this->hire_certified_by,
            'hire_prepared_by' => $this->hire_prepared_by,
            'advance_received_by' => $this->advance_received_by,
            'loading_remarks' => $this->loading_remarks,
            'loaded_by' => $this->loaded_by,
            'final_paid_to' => $this->final_paid_to,
            'detention_amount' => $this->detention_amount,
            'extra_hire_amount' => $this->extra_hire_amount,
            'final_other_amount' => $this->final_other_amount,
            'final_total_extra_amount' => $this->final_total_extra_amount,
            'grand_total_amount' => $this->grand_total_amount,
            'less_advance_other_branch_amount' => $this->less_advance_other_branch_amount,
            'less_deduction_claims_amount' => $this->less_deduction_claims_amount,
            'total_less_amount' => $this->total_less_amount,
            'final_balance_paid_at' => $this->final_balance_paid_at,
            'final_balance_code' => $this->final_balance_code,
            'final_balance_on' => $this->final_balance_on,
            'net_amount_payable' => $this->net_amount_payable,
            'final_cash_cheque_no' => $this->final_cash_cheque_no,
            'final_cash_cheque_on' => $this->final_cash_cheque_on,
            'final_bank' => $this->final_bank,
            'final_rupees_only' => $this->final_rupees_only,
            'final_passed_by' => $this->final_passed_by,
            'final_certified_by' => $this->final_certified_by,
            'final_prepared_by' => $this->final_prepared_by,
            'final_payment_received_by' => $this->final_payment_received_by,
            'received_no_bilties' => $this->received_no_bilties,
            'contract_no' => $this->contract_no,
            'owner_customer_id' => $this->owner_customer_id,
            'driver_customer_id' => $this->driver_customer_id,
            'broker_customer_id' => $this->broker_customer_id,

            // CRITICAL FIX: Use whenLoaded() instead of when(exists()) to prevent N+1 queries

            // whenLoaded() only serializes if the relation was eager loaded - NO extra queries
            'items' => $this->whenLoaded('items', fn () => InvoiceItemResource::collection($this->items)),
            'customer' => $this->whenLoaded('customer', fn () => new CustomerResource($this->customer)),
            'consignee_customer' => $this->whenLoaded('consigneeCustomer', fn () => new CustomerResource($this->consigneeCustomer)),
            'creator' => $this->whenLoaded('creator', fn () => new UserResource($this->creator)),
            'taxes' => $this->whenLoaded('taxes', fn () => TaxResource::collection($this->taxes)),
            'fields' => $this->whenLoaded('fields', fn () => CustomFieldValueResource::collection($this->fields)),
            'company' => $this->whenLoaded('company', fn () => new CompanyResource($this->company)),
            'currency' => $this->whenLoaded('currency', fn () => new CurrencyResource($this->currency)),
        ];
    }
}
